project:
  output-dir: _output

bibliography: mbon-sdm.bib

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    embed-resources: false
    mermaid:
      theme: neutral
    theme:
      dark: darkly
      light: flatly


search: false
